server:
  port: 8080

spring:
  application:
    name: demo-platafoma-engine
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:enginedb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect


camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      first-name: admin
    deployment-resource-pattern: ../bpmns/*

#demo-platafoma-engine
#demo-plataforma-simulacao-api